# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.FloatField()),
                ('w', models.FloatField()),
                ('w_pct', models.FloatField()),
                ('min', models.FloatField()),
                ('fgm', models.FloatField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.FloatField()),
                ('fg3a', models.FloatField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.FloatField()),
                ('fta', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.FloatField()),
                ('dreb', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('tov', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('pf', models.FloatField()),
                ('pfd', models.FloatField()),
                ('pts', models.FloatField()),
                ('plus_minus', models.FloatField()),
                ('dd2', models.FloatField()),
                ('td3', models.FloatField()),
                ('off_rating', models.FloatField()),
                ('def_rating', models.FloatField()),
                ('net_rating', models.FloatField()),
                ('ast_to', models.FloatField()),
                ('efg_pct', models.FloatField()),
                ('ts_pct', models.FloatField()),
                ('usg_pct', models.FloatField()),
                ('pie', models.FloatField()),
                ('pts_2nd_chanCE', models.FloatField()),
                ('point_guard', models.FloatField()),
                ('shooting_guard', models.FloatField()),
                ('small_forward', models.FloatField()),
                ('power_forward', models.FloatField()),
                ('center', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.FloatField()),
                ('w', models.FloatField()),
                ('w_pct', models.FloatField()),
                ('min', models.FloatField()),
                ('fgm', models.FloatField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.FloatField()),
                ('fg3a', models.FloatField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.FloatField()),
                ('fta', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.FloatField()),
                ('dreb', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('tov', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('pf', models.FloatField()),
                ('pfd', models.FloatField()),
                ('pts', models.FloatField()),
                ('plus_minus', models.FloatField()),
                ('dd2', models.FloatField()),
                ('td3', models.FloatField()),
                ('off_rating', models.FloatField()),
                ('def_rating', models.FloatField()),
                ('net_rating', models.FloatField()),
                ('ast_to', models.FloatField()),
                ('efg_pct', models.FloatField()),
                ('ts_pct', models.FloatField()),
                ('usg_pct', models.FloatField()),
                ('pie', models.FloatField()),
                ('pts_2nd_chanCE', models.FloatField()),
                ('point_guard', models.FloatField()),
                ('shooting_guard', models.FloatField()),
                ('small_forward', models.FloatField()),
                ('power_forward', models.FloatField()),
                ('center', models.FloatField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField()),
                ('future_salary', models.FloatField()),
                ('worth', models.FloatField()),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnnba.MLModel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnnba.Player')),
            ],
        ),
        migrations.AddField(
            model_name='coefficients',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnnba.MLModel'),
        ),
    ]
