# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('paid', models.FloatField(default=0)),
                ('projected_salaries', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOV_PCT', models.FloatField(null=True)),
                ('TS_PCT', models.FloatField(null=True)),
                ('FG2_PCT', models.FloatField(null=True)),
                ('TRB_PCT', models.FloatField(null=True)),
                ('PTS_PER_G', models.FloatField(null=True)),
                ('FG2_PER_G', models.FloatField(null=True)),
                ('TOV_PER_G', models.FloatField(null=True)),
                ('ORB_PER_G', models.FloatField(null=True)),
                ('BPM', models.FloatField(null=True)),
                ('PF_PER_G', models.FloatField(null=True)),
                ('USG_PCT', models.FloatField(null=True)),
                ('FG_PCT', models.FloatField(null=True)),
                ('FG3_PCT', models.FloatField(null=True)),
                ('DRB_pct', models.FloatField(null=True)),
                ('FTA_PER_FGA_PCT', models.FloatField(null=True)),
                ('STL_PER_G', models.FloatField(null=True)),
                ('BLK_PCT', models.FloatField(null=True)),
                ('OWS', models.FloatField(null=True)),
                ('WS', models.FloatField(null=True)),
                ('FG3A_PER_FGA_PCT', models.FloatField(null=True)),
                ('EFG_PCT', models.FloatField(null=True)),
                ('FG3_PER_G', models.FloatField(null=True)),
                ('AST_PER_G', models.FloatField(null=True)),
                ('FT_PER_G', models.FloatField(null=True)),
                ('FTA_PER_G', models.FloatField(null=True)),
                ('BLK_PER_G', models.FloatField(null=True)),
                ('ORB_PCT', models.FloatField(null=True)),
                ('STL_PCT', models.FloatField(null=True)),
                ('VORP', models.FloatField(null=True)),
                ('DBPM', models.FloatField(null=True)),
                ('WS_PER_48', models.FloatField(null=True)),
                ('DWS', models.FloatField(null=True)),
                ('PER', models.FloatField(null=True)),
                ('OBPM', models.FloatField(null=True)),
                ('TRB_PER_G', models.FloatField(null=True)),
                ('AST_PCT', models.FloatField(null=True)),
                ('FT_PCT', models.FloatField(null=True)),
                ('MIN_X_NET_RATIN', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worth', models.FloatField()),
                ('difference', models.FloatField(null=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnnba.MLModel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnnba.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nnnba.PlayerStats'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='coefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nnnba.PlayerStats'),
        ),
    ]
