# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='DRB_pct',
            new_name='DRB_PCT',
        ),
    ]
