# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0002_auto_20170728_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='future_salary',
            new_name='projected_salaries',
        ),
    ]
