# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0004_auto_20170811_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='projected_salaries',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playervalue',
            name='difference',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playervalue',
            name='worth',
            field=models.FloatField(),
        ),
    ]
