# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0005_auto_20170731_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playervalue',
            old_name='model_name',
            new_name='ml_model',
        ),
    ]
