# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0009_auto_20170731_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.FloatField(null=True)),
                ('w', models.FloatField(null=True)),
                ('w_pct', models.FloatField(null=True)),
                ('min', models.FloatField(null=True)),
                ('fgm', models.FloatField(null=True)),
                ('fg_pct', models.FloatField(null=True)),
                ('fg3m', models.FloatField(null=True)),
                ('fg3a', models.FloatField(null=True)),
                ('fg3_pct', models.FloatField(null=True)),
                ('ftm', models.FloatField(null=True)),
                ('fta', models.FloatField(null=True)),
                ('ft_pct', models.FloatField(null=True)),
                ('oreb', models.FloatField(null=True)),
                ('dreb', models.FloatField(null=True)),
                ('reb', models.FloatField(null=True)),
                ('ast', models.FloatField(null=True)),
                ('tov', models.FloatField(null=True)),
                ('stl', models.FloatField(null=True)),
                ('blk', models.FloatField(null=True)),
                ('pf', models.FloatField(null=True)),
                ('pfd', models.FloatField(null=True)),
                ('pts', models.FloatField(null=True)),
                ('plus_minus', models.FloatField(null=True)),
                ('dd2', models.FloatField(null=True)),
                ('td3', models.FloatField(null=True)),
                ('off_rating', models.FloatField(null=True)),
                ('def_rating', models.FloatField(null=True)),
                ('net_rating', models.FloatField(null=True)),
                ('ast_to', models.FloatField(null=True)),
                ('efg_pct', models.FloatField(null=True)),
                ('ts_pct', models.FloatField(null=True)),
                ('usg_pct', models.FloatField(null=True)),
                ('pie', models.FloatField(null=True)),
                ('pts_2nd_chance', models.FloatField(null=True)),
                ('point_guard', models.FloatField(null=True)),
                ('shooting_guard', models.FloatField(null=True)),
                ('small_forward', models.FloatField(null=True)),
                ('power_forward', models.FloatField(null=True)),
                ('center', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ast_to',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='center',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='dd2',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='def_rating',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='dreb',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='efg_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fg3_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fg3a',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fg3m',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fg_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fgm',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ft_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='fta',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ftm',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='min',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='net_rating',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='off_rating',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='oreb',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='pfd',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='pie',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='plus_minus',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='point_guard',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='power_forward',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='pts',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='pts_2nd_chance',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='reb',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='shooting_guard',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='small_forward',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='stl',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='td3',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='tov',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ts_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='usg_pct',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='w',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='w_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ast_to',
        ),
        migrations.RemoveField(
            model_name='player',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='center',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dd2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='def_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dreb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='efg_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fg3_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fg3a',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fg3m',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fg_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fgm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ft_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fta',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ftm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='min',
        ),
        migrations.RemoveField(
            model_name='player',
            name='net_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='off_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='oreb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pfd',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pie',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plus_minus',
        ),
        migrations.RemoveField(
            model_name='player',
            name='point_guard',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_forward',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pts_2nd_chance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='reb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shooting_guard',
        ),
        migrations.RemoveField(
            model_name='player',
            name='small_forward',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stl',
        ),
        migrations.RemoveField(
            model_name='player',
            name='td3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tov',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ts_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='usg_pct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='w',
        ),
        migrations.RemoveField(
            model_name='player',
            name='w_pct',
        ),
        migrations.AddField(
            model_name='coefficients',
            name='coefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nnnba.PlayerStats'),
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nnnba.PlayerStats'),
        ),
    ]
