# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnnba', '0010_auto_20170731_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coefficients',
            name='coefs',
        ),
        migrations.RemoveField(
            model_name='coefficients',
            name='ml_model',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='coefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nnnba.PlayerStats'),
        ),
        migrations.DeleteModel(
            name='Coefficients',
        ),
    ]
